apiVersion: equinix.harvesterhci.io/v1
kind: InstancePool
metadata:
  name: harvester-pxe-worker
spec:
  count: 1
  billingCycle: hourly
  managementInterface:
    - eth0
  plan: c3.small.x86
  metro: SG
  nodeCleanupWaitInterval: 5m
  managementBondingOptions:
    mode: balance-tlb
    miimon: "100"
  isoUrl: https://releases.rancher.com/harvester/v1.0.0-rc1/harvester-v1.0.0-rc1-amd64.iso