#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p bin

GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o bin/harvester-equinix-addon ./

mkdir -p dist/artifacts
cp -r bin/harvester-equinix-addon dist/artifacts/
