apiVersion: apps/v1
kind: Deployment
metadata:
  name: equinix-addon-controller
spec:
  selector:
    matchLabels:
      app: equinix-addon-controller
  template:
    metadata:
      labels:
        app: equinix-addon-controller
    spec:
      containers:
      - env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- if .Values.proxy }}
        - name: HTTP_PROXY
          value: {{ .Values.proxy }}
        - name: HTTPS_PROXY
          value: {{ .Values.proxy }}
        - name: NO_PROXY
          value: {{ .Values.noProxy }}
        {{- end }}
        image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
        name: equinix-addon-controller
        imagePullPolicy: "{{ .Values.image.imagePullPolicy }}"
        volumeMounts:
        - mountPath: /etc/rancher/rancherd/config.yaml
          name: rancherd
      serviceAccountName: equinix-addon-controller
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: rancherd
        hostPath:
          path: /etc/rancher/rancherd/config.yaml
          type: File

