apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: equinix-addon-controller
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: equinix-addon-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: equinix-addon-controller
subjects:
- kind: ServiceAccount
  name: equinix-addon-controller
  namespace: {{.Release.Namespace}}

